---
title: "Week8_AdvancedPlot"
author: "Retno K. Ningrum"
date: "2024-10-22"
output: html_document
---

```{r}
install.packages("patchwork") # for bringing plots together
install.packages("ggrepel") # for repelling labels
#install.packages("gganimate") # animations
install.packages("magick") # for images
```
### Load Libraries
```{r}
library(tidyverse)
library(here)
library(patchwork)
library(ggrepel)
library(gganimate)
library(magick)
library(palmerpenguins)
```
### Patchwork
to add plot 1 and plot 2
```{r}
# plot 1
p1<-penguins %>%
  ggplot(aes(x = body_mass_g, 
             y = bill_length_mm, 
             color = species))+
  geom_point()
p1

# plot 2
p2<-penguins %>%
  ggplot(aes(x = sex, 
             y = body_mass_g, 
             color = species))+
  geom_jitter(width = 0.2)
p2

#bring the plot together
p1+p2

#group the legends
p1+p2+ 
  plot_layout(guides = 'collect')

#add labels (A,B)
p1+p2+ 
  plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = 'A')

#put one plot on top the other
p1/p2+ 
  plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = 'A')
```
### ggrepel
easy and clear labels for plots
```{r}
#use the mtcars
view(mtcars)

ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text() + # creates a text label
  geom_point(color = 'red')

#repel the label
ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text_repel() + # repel the text label from the point, supaya mudah bacanya
  geom_point(color = 'red')

#repel label using box
ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_label_repel() + # repel them
  geom_point(color = 'red')



```

### gganimate
make your figure an animation
```{r}
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point()

#Add a transition
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition.
     state_length = 1 # The length of the pause between transitions
   )

#set aesthetic for transition
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition.
     state_length = 1 # The length of the pause between transitions
   )+
  ease_aes("bounce-in-out")

#add labels in the transition
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point() +
  transition_states(
     year, # what are we animating by
     transition_length = 2, #The relative length of the transition.
     state_length = 1 # The length of the pause between transitions
   )+
  ease_aes("bounce-in-out")+
  labs(title = 'Year:{closest_state}')+ #term closest state is the argument of transition
  anim_save(here("week8", "week8_class", "output", "animate_penguin.gif"))
```
### Magick package
if you want to change your images into grayscale , or placing it on top of your plot, etc
```{r}
#read an image of penguin
penguin<-image_read("https://pngimg.com/uploads/penguin/pinguin_PNG9.png")
penguin

#create plot first
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point()+
   ggsave(here("Week8","week8_class", "output","penguinplot.png"))


#put the image with magick
penplot<-image_read(here("Week8","week8_class", "output","penguinplot.png")) #whatever you wanna put in the background, you should read it first
out <- image_composite(penplot, penguin, offset = "+70+30") #penplot in the 1st layer, penguin in the second layer, offsett mean 70% out in the botom and 30% in the right
out

#can do it with gifs
# Read in a penguin gif
pengif<-image_read("https://media3.giphy.com/media/H4uE6w9G1uK4M/giphy.gif")
outgif <- image_composite(penplot, pengif, gravity = "center")
animation <- image_animate(outgif, fps = 10, optimize = TRUE)
animation
```

