---
title: "Homework Week 5: JOIN and LUBRIDATE"
author: "Retno K. Ningrum"
date: "2024-09-30"
output: html_document
---

### CALL ALL THE PACKAGE LIBRARIES 
```{r}
library(tidyverse)   #lots of function to tidying the data
library(here)        #to read the data using here(), to connect with github folder
library(lubridate)   #to assign datetime format
library(ggplot2)     #to use ggplot package, create the plot
library(gganimate)   # to use the animation package
library(gifski)      #need this to render for the gif output 
library(av)          #need this to show the video visual
```

### READ AND INSPECT THE DATA
```{r}
#Read conductivity data
Cond_df <- read_csv(here("week5", "week5_homework", "data", "CondData.csv"))

#Read depth data
Dept_df <- read_csv(here("week5", "week5_homework", "data", "DepthData.csv"))

#Inspect data
glimpse(Cond_df)  #inspect conductivity data
glimpse(Dept_df)  #inspect depth data

#NOTES based on the data inspection: "date" in conductivity is still in character, while in depth is already in datetime format. So we need to change the format "date" of cond_df into datetime

#apply datetime format at "date" column
Cond_df <- Cond_df %>%
  mutate(date = mdy_hms(date)) %>%             #assign the datetime format at "date" column
  mutate(date = round_date(date, "10 sec"))    #round to the nearest 10 seconds
  

glimpse(Cond_df)  #inspect the data again, here the "date" is in the datetime format. 
```

### JOIN THE TWO DATAFRAMES
```{r}
All_df <- inner_join(Cond_df, Dept_df, by = "date")  #use semi_join() to not join data with NAs
anyNA(All_df)  #double check, if there is NAs in the data, resuld shows "FALSE", meaning no NAs.
glimpse(All_df)
```
### Calculate the average of date, depth, temperature, and salinity by minutes
```{r}
Summarized_df <- All_df %>%                            #use the All_df to create new summarized_df
  mutate(date_minute = floor_date(date, "minute")) %>% #round to the nearest minutes, assign it to new column
  group_by(date_minute) %>%                            #group by minutes, using the new column "date_minute" 
  summarise(                                           #summarize, using summarise() function
    mean_temp = mean(Temperature, na.rm = TRUE),    #calculate mean temperature by following grouped column 
    mean_sali = mean(Salinity, na.rm = TRUE),       #calculate mean salinity by following grouped column
    mean_press = mean(AbsPressure, na.rm = TRUE),   #calculate mean pressure by following grouped column
    mean_dept = mean(Depth, na.rm = TRUE)           #calculate mean depth by following grouped column
  )
  
```

### Create the plot!
```{r}
#Before create plot, I want to use facet_wrap() features by parameter, so I need to transform into long data format
Summarized_long_df <- Summarized_df %>%
  pivot_longer(cols = c(mean_temp, mean_sali, mean_press, mean_dept), # Columns to pivot
               names_to = "parameter",                            # New column for variable names
               values_to = "value") %>%                           # New column for variable values
   mutate(parameter = recode(parameter,                           # Recode variable names for better labels
                           mean_temp = "Mean Temperature",
                           mean_sali = "Mean Salinity",
                           mean_press = "Mean Abs Pressure",
                           mean_dept = "Mean Depth"))

#Create the animated plot using gganimate
animated_plot <- ggplot(Summarized_long_df,                      #use summarized_df, 
                        aes(x = date_minute,
                        y = value ,
                        color = parameter)) +             #assign the x axis by date_minutes
  geom_line() +
  facet_wrap(~parameter, scales = "free_y") +
  labs(x = "Time",                                                                    #label the x axis   
       y = "Averages",                                                                #label the y axis
       title = "Averages of Temperature, Salinity, Pressure, and Depth by Minute") +  #the title
  theme_minimal() +   
  theme(
    plot.title = element_text(size = 20, face = "bold"),  #set the size at the title and bold the text
    axis.title.x = element_text(size = 16),               #set size of x axis
    axis.title.y = element_text(size = 16),               #set size of y axis
    axis.text = element_text(size = 14),                  #set size of axis text
    legend.title = element_text(size = 16),               #set size of legend title
    legend.text = element_text(size = 14),                #set size of legend text
    strip.text = element_text(size = 16, face = "bold"),  #set size of each frame title text, and bold
    legend.position = "none") +                             #removes legend
    transition_reveal(date_minute)                          #Animate the plot over time using date_minute

# Step 4: Render the animation
animate(animated_plot, nframes = 200,   #make into 200frames
        fps = 10,                       #set the frame by 10 frame per seconds
        width = 1200, height = 600)     #set the width and length of the frames

#Save the animated plot into the output folder
anim_save(here("week5","week5_homework", "output", "mean_parameters.gif"))
        
```

