---
title: "Week4_class"
author: "Retno K. Ningrum"
date: "2024-09-17"
output: html_document
---
```{r}
### load libraries
library(palmerpenguins)
library(tidyverse)
library(here)

#load the data and check the data before we do the manipulation
glimpse(penguins)
head(penguins)

```
```{r}
## try the filter() function
filter(.data = penguins, sex == "female")
# "=" mean sets an argument to the future
# "==" is exactly same to 

filter(.data = penguins, year == "2008") #filter data in year 2008
filter(.data = penguins, body_mass_g > 5000) #filter data where body mass is greater than 5000

filter(.data = penguins, sex == "female" & body_mass_g > 5000) # "& and comma is the same
filter(.data = penguins, sex == "female" , body_mass_g > 5000)
filter(.data = penguins, sex == "females" | body_mass_g > 5000) # or


filter(.data = penguins, year %in% c("2008","2009"))
filter(.data = penguins, island != "Dream")                      # data from island except dream
filter(.data = penguins, species %in% c("Adelie","Gentoo"))

filter(.data = penguins,
       body_mass_g <5000,
       body_mass_g > 300)



#### MUTATE == add a new data column 
data2 <- mutate(.data = penguins, body_mass_kg = body_mass_g / 1000)
view(data2)

## add multiple data column
data2 <- mutate(.data = penguins, 
                body_mass_kg = body_mass_g / 1000,
                bill_length_depth = bill_length_mm/bill_depth_mm)



```

