---
title: "Week4_class"
author: "Retno K. Ningrum"
date: "2024-09-17"
output: html_document
---
```{r}
### load libraries
library(palmerpenguins)
library(tidyverse)
library(here)

#load the data and check the data before we do the manipulation
glimpse(penguins)
head(penguins)

```
```{r}
## try the filter() function
filter(.data = penguins, sex == "female")
# "=" mean sets an argument to the future
# "==" is exactly same to 

filter(.data = penguins, year == "2008") #filter data in year 2008
filter(.data = penguins, body_mass_g > 5000) #filter data where body mass is greater than 5000

filter(.data = penguins, sex == "female" & body_mass_g > 5000) # "& and comma is the same
filter(.data = penguins, sex == "female" , body_mass_g > 5000)
filter(.data = penguins, sex == "females" | body_mass_g > 5000) # or


filter(.data = penguins, year %in% c("2008","2009"))
filter(.data = penguins, island != "Dream")                      # data from island except dream
filter(.data = penguins, species %in% c("Adelie","Gentoo"))

filter(.data = penguins,
       body_mass_g <5000,
       body_mass_g > 300)



#### MUTATE == add a new data column 
data2 <- mutate(.data = penguins, body_mass_kg = body_mass_g / 1000)
view(data2)

## add multiple data column
data2 <- mutate(.data = penguins, 
                body_mass_kg = body_mass_g / 1000,
                bill_length_depth = bill_length_mm/bill_depth_mm)

#assign new data column
data2<- mutate(.data = penguins,
               after_2008 = ifelse(year>2008, "After 2008", "Before 2008"))
View(data2)

data2 <- mutate(.data = penguins, 
                penguin_size = bill_length_mm + body_mass_g, 
                penguin_category = ifelse(body_mass_g > 5000, "Big", "Small"))
view(data2)


##### PIPING THE DATA
penguins %>% # use penguin dataframe
  filter(sex == "female") %>% #select females
  mutate(log_mass = log(body_mass_g)) #calculate log biomass


#### select() function
penguins %>% # use penguin dataframe
  filter(sex == "female") %>% #select females
  mutate(log_mass = log(body_mass_g)) %>% #calculate log biomass
  select(species, island, sex, log_mass) #select only these column

penguins %>% # use penguin dataframe
  filter(sex == "female") %>% #select females
  mutate(log_mass = log(body_mass_g)) %>% #calculate log biomass
  select(!species) #select all except species

#if you want to rename the column 
penguins %>% # use penguin dataframe
  filter(sex == "female") %>% #select females
  mutate(log_mass = log(body_mass_g)) %>% #calculate log biomass
  select(Species = species, Island = island, Sex = sex, Log_mass = log_mass) #select only these column

#### do the summary but dont count the NA value
 penguins %>% # 
  summarise(mean_flipper = mean(flipper_length_mm, na.rm=TRUE))
 
 penguins %>% # 
  summarise(mean_flipper = mean(flipper_length_mm, na.rm=TRUE),
            min_flipper = min(flipper_length_mm, na.rm=TRUE))

 #### group_by() function 
 penguins %>%
  group_by(island) %>%
  summarise(mean_bill_length = mean(bill_length_mm, na.rm = TRUE),
            max_bill_length = max(bill_length_mm, na.rm=TRUE))
 
#### removes NA
 penguins %>%
  drop_na(sex) %>% #any NA in sex column, drop it! %>%
 group_by(island, sex) %>%
   summarise(mean_bill_length = mean(bill_length_mm, na.rm = T),
             Max_bill_length = max(bill_length_mm, na.rm = T))
 
 ### adding ggplot to data without NA
 penguins %>%
  drop_na(sex) %>%
  ggplot(aes(x = sex, y = flipper_length_mm)) +
  geom_boxplot()
 
 
```

