---
title: "week13 - For loops"
author: "Retno K. Ningrum"
date: "2024-12-03"
output: html_document
---

```{r}
library(tidyverse)
library(here)
```
```{r}
#start with a simple code
print(paste("The year is", 2000))

years <- c(2015:2021)

for (i in years) {
  print(paste("The Year is", i))
}

year_df <- tibble(year = rep(NA, length(years)),
                  year_name = rep(NA, length(years)))
year_df


for (i in 1:length(years)){ # set up the for loop where i is the index
  year_df$year_name[i]<-paste("The year is", years[i]) # loop over year name
  year_df$year[i]<-years[i] # loop over year
}
year_df

```

```{r}
testdata<-read_csv(here("Week_13", "data", "cond_data","011521_CT316_1pcal.csv"))
glimpse(testdata)
```
```{r}
# point to the location on the computer of the folder
CondPath<-here("Week_13", "data", "cond_data")

# list all the files in that path with a specific pattern
# In this case we are looking for everything that has a .csv in the filename
# you can use regex to be more specific if you are looking for certain patterns in filenames
files <- dir(path = CondPath,pattern = ".csv") #dir is directory, pattern means find everything .csv
files
```
```{r}
# mau buat list data terkait file yang kita punya
# pre-allocate space
# make an empty dataframe that has one row for each file and 3 columns
 cond_data<-tibble(filename =  rep(NA, length(files)),  # column name for year
                   mean_temp = rep(NA, length(files)), # column name for the mean temperature
                   mean_sal = rep(NA, length(files)), # column name for the mean salinity
                   ) # column name for the year name
 cond_data
 #next bisa masukin informasinya dg for loop
```
```{r}
#hanya untuk ngetes aja kalo kodenya bener
raw_data<-read_csv(paste0(CondPath,"/",files[1])) # test by reading in the first file and see if it works
head(raw_data)
```
```{r}
for (i in 1:length(files)){ # loop over 1:3 the number of files
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
glimpse(raw_data)
}


```
```{r}
for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
#glimpse(raw_data)
cond_data$filename[i]<-files[i]
cond_data$mean_temp[i] <- mean(raw_data$Temperature, na.rm = TRUE)
cond_data$mean_sal[i] <- mean(raw_data$Salinity, na.rm = TRUE)
} 
cond_data
```

Map Function
```{r}
#start with a sequence
1:10

#what function we want to map on each variable
1:10 %>%
  map(rnorm, n=15) #calculate 15 random normalise numbe

1:10 %>%
  map(rnorm, n=15) %>% #calculate 15 random normalise numbe
  map_dbl(mean) #calculate the mean. it is now a vector using double type


```

```{r}
1:10 %>% # list 1:10
  map(function(x) rnorm(15, x)) %>% # make your own function
  map_dbl(mean)

#Use a formula when you want to change the arguments within the function, just same thing with function(x)
1:10 %>%
  map(~ rnorm(15, .x)) %>% # changes the arguments inside the function with the "."
  map_dbl(mean)
```
```{r}
# point to the location on the computer of the folder
CondPath<-here("Week_13", "data", "cond_data")
files <- dir(path = CondPath,pattern = ".csv")
files

#Or, we can get the full file names in one less step by doing this...

files <- dir(path = CondPath,pattern = ".csv", full.names = TRUE)
#save the entire path name
files

data<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename") # map everything to a dataframe and put the id in a column called filename
data
```

```{r}

```

