---
title: "Week2"
author: "Retno K. Ningrum"
date: "2024-09-10"
output: html_document
---

```{r}
####Load libraries ####
library(palmerpenguins)
library(ggplot2)
library(tidyverse)
library(here)

###inspect the data
view(penguins)
head(penguins)
tail(penguins)
glimpse(penguins)

```

```{r}
### Make a simple plot ####
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm)) +  ## this is just to create the base map (first layer), then add new layer with "+"
  geom_point() +                             #input the point value
  labs(x = "Bill depth (mm)",                #add the x and y axis label
       y = " Bill length (mm)")


## simple plot with colot
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     color = species)) +     # tell R to collor by species
  geom_point() +                             #input the point value
  labs(title = "Bill depth and length" ,     #add tittle at the map data
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", #add subtitle
       x = "Bill depth (mm)",                #add the x and y axis label
       y = " Bill length (mm)",
       color = "Species",                    #rename the legend in color into "Species"
       caption = "Source: Palmer Station LTER/ palmerpenguins package") + #add caption below the data frame
  scale_color_viridis_d() #to choose colorblind friendly color


#simple plot with different shapes
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     color = species,        # tell R to collor by species
                     shape = island)) +      # to shape by island
  geom_point() +                             #input the point value
  labs(title = "Bill depth and length" ,     #add tittle at the map data
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", #add subtitle
       x = "Bill depth (mm)",                #add the x and y axis label
       y = " Bill length (mm)",
       color = "Species",                    #rename the legend in color into "Species"
       caption = "Source: Palmer Station LTER/ palmerpenguins package") + #add caption below the data frame
  scale_color_viridis_d() 

#simple plot with different size
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     color = species,        # tell R to collor by species
                     size = body_mass_g,     # to visualize body mass in size
                     alpha = flipper_length_mm)) +  #to add transparency based on flipper length 
  geom_point() +                             #input the point value
  labs(title = "Bill depth and length" ,     #add tittle at the map data
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins", #add subtitle
       x = "Bill depth (mm)",                #add the x and y axis label
       y = " Bill length (mm)",
       color = "Species",                    #rename the legend in color into "Species"
       caption = "Source: Palmer Station LTER/ palmerpenguins package") + #add caption below the data frame
  scale_color_viridis_d() 

```

```{r}
### Facetting ####
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm)) +  ## this is just to create the base map (first layer), then add new layer with "+"
  geom_point() +                             #input the point value
  facet_grid( species ~ sex) +               #adding facet grid used if want to see by row ~ column
  labs(x = "Bill depth (mm)",                #add the x and y axis label
       y = " Bill length (mm)")



ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm)) +  ## this is just to create the base map (first layer), then add new layer with "+"
  geom_point() +                             #input the point value
  facet_wrap(~ species) +                    #adding facet wrap using one category, more simple
  labs(x = "Bill depth (mm)",                #add the x and y axis label
       y = " Bill length (mm)")



ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm)) +  ## this is just to create the base map (first layer), then add new layer with "+"
  geom_point() +                             #input the point value
  facet_wrap(~ species, ncol = 2) +          #adding facet wrap using one category, in 2 column
  labs(x = "Bill depth (mm)",                #add the x and y axis label
       y = " Bill length (mm)")


####adding color#####
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     color = species)) +  ## this is just to create the base map (first layer), then add new layer with "+"
  geom_point() +                             #input the point value
  facet_grid(species ~ sex) +          #adding facet wrap using one category, in 2 column
  labs(x = "Bill depth (mm)",                #add the x and y axis label
       y = " Bill length (mm)") +
  scale_colour_viridis_d()+
  guides(color = FALSE) # removing legend

```
```{r}
###Add a best fit line #####
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm)) +
  geom_point() +
  geom_smooth() +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)")

##want to use linear model in geom smooth
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)")

##Want to use by species, lm in each species
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +  #add the grouping, can use color as well to grouping 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)") +
  scale_colour_viridis_d()

```

```{r}
#####just for fun ~ a thoughtful package
install.packages("praise")
library(praise)
praise()
praise()
```
```{r}
###Scales
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)") +
  scale_colour_viridis_d() +
  scale_x_continuous(limits = c(0,20)) + #dont show data from x axis 0 to 20
  scale_y_continuous(limits = c(0,50)) #dont show data from y axis from 0 to 50


#try breaks instead of limits
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)") +
  scale_colour_viridis_d() +
  scale_x_continuous(breaks = c(14,17,21), #use this number as limits break then
                     labels = c("low", "medium", "high"))+  #then classify it into levels
  scale_color_manual(values = c("orange", "purple", "blue"))

```
```{r}
####install package devtools to call code 
## devtool is installed
library(devtools)
library(ps)

# devtools::install_github("dill/beyonce")

library(beyonce)

###try the pallete
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)") +
  scale_colour_viridis_d() +
  scale_x_continuous(breaks = c(14,17,21), #use this number as limits break then
                     labels = c("low", "medium", "high"))+  #then classify it into levels
  scale_color_manual(values = beyonce_palette(2))

```

```{r}
## COORDINATES
#coord_flip() = cartesian coordinate system with x and y axes flipped
#coord_fixed() = cartesian coordinate system with a fixed aspect ratio 
#coord_trans() = apply arbitary transformation of x and y positions after the data has been processed by the stat
#coord_polar() : polar coordinates

ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)") +
  scale_colour_viridis_d() +
  scale_x_continuous(breaks = c(14,17,21), #use this number as limits break then
                     labels = c("low", "medium", "high"))+  #then classify it into levels
  scale_color_manual(values = beyonce_palette(2))+
  coord_flip() #flip the x and y axes

ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)") +
  scale_colour_viridis_d() +
  scale_x_continuous(breaks = c(14,17,21)) + #, #use this number as limits break then
                     #labels = c("low", "medium", "high"))+  #then classify it into levels
  scale_color_manual(values = beyonce_palette(2))+
  coord_fixed() # give exactly 1:1 ratio


### change coordinates : transform x y axis (log10)
#check without log transformed
ggplot(diamonds, aes(carat, price)) +
  geom_point()

#check with logtransform
ggplot(diamonds, aes(carat, price)) +
  geom_point() +
  coord_trans(x = "log10", y = "log")


#make the data into polar, using the polar coordinate
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)") +
  scale_colour_viridis_d() +
  scale_x_continuous(breaks = c(14,17,21)) + #, #use this number as limits break then
                     #labels = c("low", "medium", "high"))+  #then classify it into levels
  scale_color_manual(values = beyonce_palette(2))+
  coord_polar()

```
```{r}
### THEME ####
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)") +
  scale_colour_viridis_d() +
  scale_x_continuous(breaks = c(14,17,21)) + #, #use this number as limits break then
                     #labels = c("low", "medium", "high"))+  #then classify it into levels
  scale_color_manual(values = beyonce_palette(2))+
  theme_bw() #CHECK website datanovia for other different theme

#change the font size
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)") +
  scale_colour_viridis_d() +
  scale_x_continuous(breaks = c(14,17,21)) + #, #use this number as limits break then
                     #labels = c("low", "medium", "high"))+  #then classify it into levels
  scale_color_manual(values = beyonce_palette(2))+
  theme_bw() +
  theme(axis.title = element_text(size = 20, #change the size of axis label
                                  color = "red"), #re-color the the font axis
                                  panel.background = element_rect(fill = "linen")) #change color of the panel

```
```{r}
####save the plot###
ggsave(here("week3", "output", "penguin.png"),
       width = 7, height = 5) #change the height and width of the final png 


#save the plot as an object
plot1 <- ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     group = species,
                     color = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs( x = "Bill depth (mm)",
        y = "Bill length (mm)") +
  scale_colour_viridis_d() +
  scale_x_continuous(breaks = c(14,17,21)) + #, #use this number as limits break then
                     #labels = c("low", "medium", "high"))+  #then classify it into levels
  scale_color_manual(values = beyonce_palette(2))+
  theme_bw() +
  theme(axis.title = element_text(size = 20, #change the size of axis label
                                  color = "red"), #re-color the the font axis
                                  panel.background = element_rect(fill = "linen")) #change color of the panel

plot1

```

