---
title: "Homework MBIO 612"
author: "Retno K. Ningrum"
date: "2024-09-11"
output: html_document
---

```{r}
##### LOAD LIBRARIES #####

library(palmerpenguins) #to use the palmerpenguin data
library(ggplot2) #to use ggplot package
library(gganimate) # to use the animation package
library(tidyverse) #lots of function to tidying the data
library(here) #to connect with github folder
library(devtools) #to call other package, Im using this to call beyonce color palette
library(ps) #need this if I want to use the devtools (it is mentioned in the warning)
library(gifski) #need this to render for the gif output 
library(av) #need this to show the video visual
library(beyonce) #need this to use beyonce color palatte
library(ggthemes) #need this to use the theme in the base of data frame

```

```{r}
###### INSPECT THE DATA #######
###inspect the data
view(penguins)
head(penguins)
tail(penguins)
glimpse(penguins)

#After inspect the data, I want to make a visualization about the bill depth and bill length of each species both female and male. in Other words, I want to use the x- axis as the bill depth, y-axis as the bill length and colored the data point by sex (male and female), then faceted it by species. I will also put the animation to see the difference overtime. 

```

```{r}
### CREATE THE PLOT ####
animated_plot <- ggplot(data = penguins, # using penguins data
       mapping = aes(x = bill_depth_mm,  #assign the x-axis with bill depth (mm)
                     y = bill_length_mm, #assign the y-axis with bill length (mm)
                     size = body_mass_g, #assign the size following the body mass (gr)
                     color = sex))  +
  geom_point(alpha = 0.7) + #this is to set the transparency of the geom point
  scale_colour_manual(values = beyonce_palette(2)) + #to set the color based on beyonce palette
  scale_size(range = c(2, 12)) + #to set the size of geom point based on mass, from 2 to 12
  facet_wrap(~species) + #to facet the grid by species
  labs(title = "Bill and Body Mass Dimension", #to assign the title of the figures
       subtitle = 'Year: {frame_time}',        #to add subtitle with the adjusting year
       x = 'Bill Depth (mm)',                  #to rename the x axis label
       y = 'Bill Length (mm)',                 #to rename the y axis label
       color = "Sex",                          #to rename the sex legend
       size = "Body Mass (gr)",                #to rename the size legend
       caption = "Source: Palmer Station LTER/ palmerpenguins package") + #to add caption below the data frame)
  transition_time(year) + #to set the time transition by year
  ease_aes('linear') + # to ensures that all changes progress evenly over time without any acceleration or deceleration.
  theme_bw() #to use the theme_bw() as the base figures

animate(animated_plot) #to render the animated plot, can check the result in the viewer

anim_save(here("week3","week3_homework", "output"),
          width = 5, height = 5)


#####VISUAL ANALYSIS##########

#The bill and body mass size between male and female is different among three different species, where it seems most of the male is larger than the female. Among three different species, Gentoo has the higher body mass and Adelie has a tendency to have lower body mass. In term of the bill depth, Gento has lower bill depth compare to other two species. However, the bill length spread were similar to chinstrap. In term of time, it seems in 2009 the variance of bill length is more varies at Adelie and Gentoo compare to 2007. But again all these conclusion still needs further statistical analysis to have a solid inference. 


```



